CREATE USER c##test IDENTIFIED BY 87654321
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;
GRANT CONNECT, RESOURCE TO c##test;
GRANT ALL PRIVILEGES TO c##test;
GRANT DBA TO c##test;
GRANT UNLIMITED TABLESPACE TO c##test;