import { MigrationInterface, QueryRunner } from "typeorm";

export class BancoPlanilla1739822091459 implements MigrationInterface {
    name = 'BancoPlanilla1739822091459'

    public async up(queryRunner: QueryRunner): Promise<void> {

        await queryRunner.query(`CREATE TABLE "NET_BANCO_PLANILLA" ("ID_BANCO_PLANILLA" number GENERATED BY DEFAULT AS IDENTITY, "ID_AF_BANCO" number, "ID_PLANILLA" number, CONSTRAINT "PK_ID_BANCO_PLANILLA" PRIMARY KEY ("ID_BANCO_PLANILLA"))`);

        await queryRunner.query(`ALTER TABLE "NET_BANCO_PLANILLA" ADD CONSTRAINT "FK_ID_AF_BANCO_PER_BANCO" FOREIGN KEY ("ID_AF_BANCO") REFERENCES "NET_PERSONA_POR_BANCO" ("ID_AF_BANCO")`);
        await queryRunner.query(`ALTER TABLE "NET_BANCO_PLANILLA" ADD CONSTRAINT "FK_ID_PLANILLA_BAN_PLAN" FOREIGN KEY ("ID_PLANILLA") REFERENCES "NET_PLANILLA" ("ID_PLANILLA")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "NET_BANCO_PLANILLA" DROP CONSTRAINT "FK_ID_PLANILLA_BAN_PLAN"`);
        await queryRunner.query(`ALTER TABLE "NET_BANCO_PLANILLA" DROP CONSTRAINT "FK_ID_AF_BANCO_PER_BANCO"`);

        await queryRunner.query(`DROP TABLE "NET_BANCO_PLANILLA"`);

    }

}
